### ISSUE TITLE
Add files to img

### ISSUE THREAD

**Issue by grigohas** [celuk/gem5-riscv-linux#2]
Hello, i am trying to add a file from host to .img so i can run it through gem5 but the .img file is only 50mb and it doesnt let me add something larger. How can i enlarge it ?

**Comment by celuk** [comment]
One of these solutions should work:

https://www.google.com/search?q=resize+img+file+site:superuser.com&sca_esv=1ad7256b324010b7&sa=X&ved=2ahUKEwjFroCxoOeHAxU0SvEDHUg1NqEQrQIoBHoECCEQBQ&biw=1920&bih=951&dpr=1

especially this:

https://superuser.com/questions/693158/can-i-expand-the-size-of-a-file-based-disk-image

or this:

https://superuser.com/questions/24838/is-it-possible-to-resize-a-qemu-disk-image
