### ISSUE TITLE
internet on ucanlinux

### ISSUE THREAD

**Issue by grigohas** [celuk/gem5-riscv-linux#3]
i follow your workflow and i can launch ucanlinux on gem but i want to install some packages like glibc lib . do yoy know how can i do that ? also i get an error that cannot find eth0 device

**Comment by celuk** [comment]
Normally, you cannot reach networking in gem5 simulator with its current capabilities. However, there are some researchers that they have found a way to get networking on gem5 but for ARM architecture:

https://github.com/agsiddharth/CAL-DPDK-GEM5

https://github.com/architecture-research-group/gem5-dpdk-setup

If you can imitate them for RISCV, it will be possible to get a networking for linux distros mentioned in this repo.

Without networking, either you need to do cross compilation (via [riscv-gnu-toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain)) on your host pc from source of the program you wanted or you need to get precompiled packages such as .deb for ubuntu. Then, you need to add compiled binary/packages to your image.

**Comment by grigohas** [comment]
yeah but ucanlinux is a readonly file so i get that error when i am trying to install glibc
